Feature/follow
shinonome-inc/backend-final-assignment-taku072002T pull request #5
Opened 2024-06-30 10:25 UTC by taku072002T

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-07-01 10:31 UTC, Shiota620 commented
Logoutが正常に動作していません。
一度、確認をお願いします。

2024-07-01 10:37 UTC, Shiota620 commented
logoutができない状態ではレビューがしにくいのでここで作業を一旦中断します。
logoutについては私の環境の問題の可能性もありますので、そちらでログアウトが正常に行える場合はすぐにお知らせください。

2024-07-01 10:42 UTC, taku072002T commented
レビューありがとうございます！
こちらでは、ログアウトは正常に行えるようになっています！

2024-07-01 10:42 UTC, taku072002T commented
Discordの方に確認動画を送信しましたので、ご覧ください！

2024-07-02 05:50 UTC, Shiota620 requested changes

2024-07-02 05:50 UTC, Shiota620 commented on accounts/models.py
> +
UniqueConstraint でユニーク制約を付与してください。
これをしないと、同じ人にフォローを複数回出来るようになります。一度、同じ人のフォローを2回押してみてください。フォロワー数が2になるはずです。
補足ですが、unique_togetherは非推奨となります。

2024-07-02 05:50 UTC, Shiota620 commented on accounts/views.py
N+1問題が発生しています。
django-debug-toolbarを使って確認してください。

2024-07-02 05:50 UTC, Shiota620 commented on accounts/tests.py
tweets.testsでAttributeErrorが発生していませんか？
ご確認よろしくお願い致します。

2024-07-02 11:59 UTC, taku072002T commented
tweetsのテストを任意実行してみましたが、AttributionErrorは検出されませんでした...

2024-07-05 16:36 UTC, Shiota620 commented on accounts/models.py
> +        related_name="user",
フォロワー一覧のリンクでエラーが発生しています。
おそらくrelated_nameをuserに変更したことが原因だと思います。

2024-07-05 16:36 UTC, Shiota620 commented on accounts/models.py
> +
同じ人にフォローをするとIntegrityErrorが表示されます。
最終課題レビューポイントでは、「既にフォローしている/フォローしていない系の表示は， django.contrib.messages などで伝えてあげても良いが，特段の規定はしない。この処理を書くときは， get_or_create などを活用できるとgood」とありますが、あなたのスキルなら、get_or_createもしくはdjango.contrib.messages を用いた出力を実装してみても良いと思います。

2024-07-06 00:56 UTC, taku072002T commented
確認、修正を行いました！

2024-07-06 05:43 UTC, Shiota620 commented
フォロワー一覧のところでN+1問題が発生しています。

2024-07-06 05:51 UTC, Shiota620 requested changes

2024-07-06 05:51 UTC, Shiota620 commented on accounts/views.py
> +class FollowerListView(ListView):
フォロワー一覧のところでN+1問題が発生しています。

2024-07-06 05:51 UTC, Shiota620 commented on accounts/views.py
> +class FollowingListView(ListView):
フォロー一覧でもN+1問題が発生しています。

2024-07-06 05:59 UTC, taku072002T commented
再度修正を行いました！レビューよろしくお願いします！

2024-07-06 06:32 UTC, Shiota620 commented
最終課題レビューポイントに従ってい修正を行う場合、以下の項目が修正対象になるのではないかと考えています。

・FollowView・UnFollowViewで， View を継承して， post メソッドに処理を書いている。

・以下の3つのバリデーションを行う。（デコレータで行っているかも？）
    1.  `get_object_or_404` などによる，urlから受け取ったuserの存在チェック
        - `django.contrib.messages` を表示したいなら，existsを使ってチェック→add_message→Http404みたいな処理を書いても良い
    2. 自分自身を扱おうとしたときは400を返すチェック
    3. 正常時は302，tweets:homeにリダイレクト
        - 既にフォローしている/フォローしていない系の表示は， `django.contrib.messages` などで伝えてあげても良いが，特段の規定はしない。この処理を書くときは， `get_or_create` などを活用できるとgood

・FollowingListViewとFollowerListViewで適切なViewを用いて，フォロー・被フォローの新しい順でフォロー・フォロワー一覧を返すviewを作成している
    -ListView を使用し， get_queryset で絞り込む（一番スマート）

しかし、私はデコレータについての知識がないのと、過去のレビューを見るとプロフィールの実装方法が現在の方法でOKが出ているため、どこまで修正する必要があるのか判断できません。

申し訳ありませんが、views.pyのレビューについては、koichiさんにお願いしたいです。

また、Guntarkuさん自身は問題ないそうですが、私は画面のログアウトボタンでログアウトすることができず、管理者画面で無理やりユーザーとツイートを追加して確認したので、見落としがある可能性が高いです。
お忙しいところ恐れ入りますが、ご確認よろしくお願い致します。

2024-07-06 06:33 UTC, Shiota620 commented
これで一次レビューは終了します。お疲れ様でした。

2024-07-06 06:34 UTC, Shiota620 commented
最終課題レビューポイントに従ってい修正を行う場合、以下の項目が修正対象になるのではないかと考えています。

・FollowView・UnFollowViewで， View を継承して， post メソッドに処理を書いている。

・以下の3つのバリデーションを行う。（デコレータで行っているかも？）
    1.  `get_object_or_404` などによる，urlから受け取ったuserの存在チェック
        - `django.contrib.messages` を表示したいなら，existsを使ってチェック→add_message→Http404みたいな処理を書いても良い
    2. 自分自身を扱おうとしたときは400を返すチェック
    3. 正常時は302，tweets:homeにリダイレクト
        - 既にフォローしている/フォローしていない系の表示は， `django.contrib.messages` などで伝えてあげても良いが，特段の規定はしない。この処理を書くときは， `get_or_create` などを活用できるとgood

・FollowingListViewとFollowerListViewで適切なViewを用いて，フォロー・被フォローの新しい順でフォロー・フォロワー一覧を返すviewを作成している
    -ListView を使用し， get_queryset で絞り込む（一番スマート）

しかし、私はデコレータについての知識がないのと、過去のレビューを見るとプロフィールの実装方法が現在の方法でOKが出ているため、どこまで修正する必要があるのか判断できません。

申し訳ありませんが、views.pyのレビューについては、koichiさんにお願いしたいです。

また、Guntarkuさん自身は問題ないそうですが、私は画面のログアウトボタンでログアウトすることができず、管理者画面で無理やりユーザーとツイートを追加して確認したので、見落としがある可能性が高いです。
お忙しいところ恐れ入りますが、ご確認よろしくお願い致します。

2024-07-06 06:38 UTC, taku072002T commented
了解しました。ログアウト機能に関しては、再度確認することにします。
views.pyの機能についても、最終課題ポイントに沿うように修正を加えることにします。
レビューお疲れ様でした！

2024-07-14 05:17 UTC, lokochaol commented on accounts/views.py
> +        context = super().get_context_data(**kwargs)
38行目 `super().get_context_data(**kwags)` はどのような意図で書いていますか？

2024-07-14 05:17 UTC, lokochaol commented on accounts/views.py
> +        context = super().get_context_data(**kwargs)
上に同じですがこちらも、どのような意図で書いていますか？

2024-07-14 05:17 UTC, lokochaol commented on accounts/views.py
> +        created = Connection.objects.get_or_create(follower=follower, following=following)
get_or_createを使うアイデアはとてもいいと思います！
が使い方が怪しいように思います。
https://docs.djangoproject.com/en/5.0/ref/models/querysets/#get-or-create

2024-07-14 05:17 UTC, lokochaol commented on accounts/views.py
> +        created = Connection.objects.get_or_create(follower=follower, following=following)
この実装だと、必ずcreatedはtrueになるはずで分岐処理としても正しくないかと思います。

2024-07-14 05:17 UTC, lokochaol commented on accounts/views.py
> +        return HttpResponseBadRequest("You cannot follow yourself")
まず、エラー処理を早期リターンする実装とってもいいと思います。
知っているかもですがアリーリターンと言うそうです。https://qiita.com/Mike3906/items/e09dbc0adcf0c25fda97

2024-07-14 05:17 UTC, lokochaol commented on tweets/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="tweet_user", on_delete=models.CASCADE, default="")
逆参照のためのrelated_nameこれだと直感的な使い方ができない気がします！

2024-07-14 05:17 UTC, lokochaol commented on accounts/models.py
> +    follower = models.ForeignKey(
これは完全に僕の意見ですが、フォローする人とフォローされる人の関係はfollowerとfolloweeが直感的でわかりやすいかと思うけどどうでしょう！

2024-07-14 05:27 UTC, lokochaol commented on accounts/views.py
> +def follow_view(request, username):
関数ベースでも書いてみているんですかね！いいと思います👍
シンプルな汎用ビューもあるのでそれを継承して作るのもありだと思います！
https://ccbv.co.uk/projects/Django/5.0/django.views.generic.base/View/

2024-07-14 09:12 UTC, taku072002T commented
指摘部、修正を加えました！
再レビューよろしくお願いします！

2024-07-15 16:01 UTC, lokochaol commented on tweets/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="author", on_delete=models.CASCADE, default="")
related_name はどういうときに使われるかというと、
この場合であればUserのオブジェクトから関連するTweetのオブジェクトを逆引きする際に使います。
具体的には
```
user_a = User.objects.all().first()
user_a_tweets = user_a.related_name
```
と言うようにuser_aに紐づくtweetのsetを取得する際に使います。

この場合はデフォルト値を使うのも手です。
related_name を設定しない場合のデフォルト値:
ForeignKey: <model_name>_set という逆参照名が使用される。
ManyToManyField: 同じく <model_name>_set という逆参照名が使用される。

`user_a.auther`とした時にuser_aのツイートのクエリセットが取得される実装になるかと思うのが
ちょっと違和感あるかなと思います！

2024-07-17 14:31 UTC, lokochaol commented on tweets/models.py
> +    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default="")
後から加えてで申し訳ないんですが、ForeginKeyのフィールドにdefaut値はそれに意味を持たせたい場合を除いて設定しないが一般的かと思います。
必ずしもこのフィールドに値が入らなくても良い場合に、null=Trueとすることはあるかと思いますが。

2024-07-17 14:42 UTC, lokochaol commented on tweets/models.py
>      id = models.UUIDField(primary_key=True, blank=True, null=False, default=uuid.uuid4, editable=False)
primary_keyは、一つのデータに対して必ず存在しなければならないものです！
そのデータを一意に判別するため↑

なので、データベースでblank=Trueやnull=Trueにすることはまずないと思います！

また、
https://docs.djangoproject.com/en/5.0/ref/models/fields/#null
に記載があるように、デフォルトでnull=Falseになっているため、明記することで意味を持たせる場合以外はこれを記載する必要はないかと思います！

2024-07-18 07:06 UTC, taku072002T commented
修正を加えました！
再レビューよろしくお願いします！
毎度ありがとうございます！

2024-07-18 13:50 UTC, lokochaol approved these changes

2024-07-18 13:52 UTC, lokochaol commented
LGTM！

2024-07-18 13:53 UTC, merged