Made Setting for test,and merged before branch main
shinonome-inc/backend-final-assignment-taku072002T pull request #7
Opened 2024-07-20 11:55 UTC by taku072002T

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-07-31 04:43 UTC, HasegawaKota reviewed
以下の点を直してみてください！
①今回のいいね機能の実装では非同期通信で実装する必要があるため、Ajax の FetchAPI(JavaScriptのなんか)を使ってください！

②いいね機能の実装範囲とは違ってしまうのですが、ホーム画面において他者のプロフィールのリンクを貼ってください。今のままだとURLをいじらないとアクセスしたい相手のプロフィールに飛ぶことが出来ないので...

2024-09-06 11:28 UTC, taku072002T commented
ご指摘点、修正しました！
再レビューよろしくお願いします！

2024-09-09 15:27 UTC, HasegawaKota approved these changes

2024-09-11 01:55 UTC, IzmYuta requested changes
よく書けていると思います！
ただ、何ヶ所か疑問に思った部分があったので返信or修正お願いします！

2024-09-11 01:55 UTC, IzmYuta commented on tweets/models.py
> +class Favorite(models.Model):
ViewではLike・Unlikeとしている一方で、ModelではFavoriteと命名した理由は何ですか？

2024-09-11 01:55 UTC, IzmYuta commented on tweets/tests.py
> +        self.wrongurl = reverse_lazy("tweets:like", kwargs={"pk": "48956984-1c8b-6e38-2d6a-548a6b1c50f0"})
このURLが100%間違いである保証はありますか？

2024-09-11 01:55 UTC, IzmYuta commented on tweets/views.py
> +        tweet.number = i + 1
tweet.numberは何のための数値ですか？

2024-09-11 01:55 UTC, IzmYuta commented on tweets/views.py
> +    tweets_number = tweets_list.count()
numberという命名はやや曖昧なので多用しないことをおすすめします。
数量として表す場合はcountと命名するのが適切だと思います。

適切な語がなく、使わざるを得ない場合でも「〜の数」のようにnumberを修飾して意味を明確にしましょう。

2024-09-11 01:55 UTC, IzmYuta commented on tweets/views.py
> +        _, created = Favorite.objects.get_or_create(user=user, tweet=tweet)
createdは使われていますか？

2024-09-11 01:55 UTC, IzmYuta commented on accounts/views.py
> +        if Favorite.objects.filter(user=request.user, tweet=tweet).exists():
for文内でのDB操作は極力避けましょう(N+1問題)
request.userがいいねをしたツイートIDを取得することは、for文外でも可能だと思います。

2024-09-11 01:55 UTC, IzmYuta commented on accounts/views.py
> +        tweet.n_liked = Favorite.objects.filter(tweet=tweet).all().count()
いいね数も同様です。

2024-09-11 01:55 UTC, IzmYuta commented on tweets/views.py
> +    tweets_number = tweets_list.count()
N+1問題。

2024-09-11 02:03 UTC, taku072002T commented on tweets/models.py
> +class Favorite(models.Model):
参考記事に引っ張られた命名になっていたと思います。

2024-09-11 02:06 UTC, taku072002T commented on tweets/tests.py
> +        self.wrongurl = reverse_lazy("tweets:like", kwargs={"pk": "48956984-1c8b-6e38-2d6a-548a6b1c50f0"})
ご指摘の通り、全くありません....
次のコミットで絶対に間違っているURLに直します。

2024-09-11 02:08 UTC, taku072002T commented on tweets/views.py
> +        tweet.number = i + 1
tweet.numberは、tweets/home.htmlにおいて、Ajax操作を行う時、それぞれのツイートに対して別々のタグを振り分けるためのIDとして扱っています。

2024-09-11 02:09 UTC, taku072002T commented on tweets/views.py
> +    tweets_number = tweets_list.count()
勉強になります。
次のコミットでそのように改修します！

2024-09-11 02:13 UTC, taku072002T commented on tweets/views.py
> +        _, created = Favorite.objects.get_or_create(user=user, tweet=tweet)
createdは使われていません。
これは、もともと Favoriteが作られたか作られていないかで動作を分けていたのですが、
よくよく考えてみたらその動作は必要なく、その名残がそのまま残っていたものでした。
次のコミットでは、フラグの代入部分を消し、等式の右側のみが残る形になると思います。

2024-09-11 02:32 UTC, taku072002T commented on accounts/views.py
> +        if Favorite.objects.filter(user=request.user, tweet=tweet).exists():
N+1問題がたくさん...
こちらも次のコミットで改修します！

2024-10-07 06:42 UTC, IzmYuta approved these changes
LGTM

2024-10-07 09:00 UTC, taku072002T commented
レビューありがとうございました！
初めて触れたコードが多くあり、良い経験になったと思います！
重ねてレビュアーの方々に感謝します！

2024-10-07 09:00 UTC, merged